import { Inter } from "next/font/google";
import "./globals.css";
import TopNavbar from "@/components/topNavbar";
import LeftSidebar from "@/components/leftSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TopNavbar />
        {/*==========BODY============== */}
        <div className="mt-4 w-[95%] mx-auto flex gap-2">
          <LeftSidebar />
          <div className="w-2/4">{children}</div>
          <div className="w-1/4"></div>
        </div>
      </body>
    </html>
  );
}
