import "./globals.css";
import LayoutComponent from "@/app/layoutComponent";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <LayoutComponent children={children} />
      </body>
    </html>
  );
}
